INSERT INTO `cities` (`city_name_fa` , `city_name_en` , `city_name_ar`, `state_id` , `deleted_at` , `created_at` , `updated_at`)
VALUES 
('آذرشهر',null , null ,1 , null , null , null),
('اسكو',null , null ,1 , null , null , null),
('اهر',null , null ,1 , null , null , null),
('بستان آباد',null , null ,1 , null , null , null),
('بناب',null , null ,1 , null , null , null),
('تبريز',null , null ,1 , null , null , null),
('جلفا',null , null ,1 , null , null , null),
('چار اويماق',null , null ,1 , null , null , null),
('سراب',null , null ,1 , null , null , null),
('شبستر',null , null ,1 , null , null , null),
('عجبشير',null , null ,1 , null , null , null),
('كليبر',null , null ,1 , null , null , null),
('مراغه',null , null ,1 , null , null , null),
('مرند',null , null ,1 , null , null , null),
('ملكان',null , null ,1 , null , null , null),
('ميانه',null , null ,1 , null , null , null),
('ورزقان',null , null ,1 , null , null , null),
('هريس',null , null ,1 , null , null , null),
('هشترود',null , null ,1 , null , null , null),
('ارومیه',null , null ,2 , null , null , null),
('اشنويه',null , null ,2 , null , null , null),
('بوکان',null , null ,2 , null , null , null),
('پير انشهر',null , null ,2 , null , null , null),
('تكاب',null , null ,2 , null , null , null),
('چالدران',null , null ,2 , null , null , null),
('خوي',null , null ,2 , null , null , null),
('سردشت',null , null ,2 , null , null , null),
('سلماس',null , null ,2 , null , null , null),
('شاهين دژ',null , null ,2 , null , null , null),
('ماكو',null , null ,2 , null , null , null),
('مهاباد',null , null ,2 , null , null , null),
('مياندوآب',null , null ,2 , null , null , null),
('نقده',null , null ,2 , null , null , null),
('اردبيل',null , null ,3 , null , null , null),
('بيله سوار',null , null ,3 , null , null , null),
('پارس آباد',null , null ,3 , null , null , null),
('خلخال',null , null ,3 , null , null , null),
('كوثر',null , null ,3 , null , null , null),
('گرمي',null , null ,3 , null , null , null),
('مشگين',null , null ,3 , null , null , null),
('نمين',null , null ,3 , null , null , null),
('نير',null , null ,3 , null , null , null),
('آران و بيدگل',null , null ,4 , null , null , null),
('اردستان',null , null ,4 , null , null , null),
('اصفهان',null , null ,4 , null , null , null),
('برخوار و ميمه',null , null ,4 , null , null , null),
('تيران و كرون',null , null ,4 , null , null , null),
('چادگان',null , null ,4 , null , null , null),
('خميني شهر',null , null ,4 , null , null , null),
('خوانسار',null , null ,4 , null , null , null),
('سميرم',null , null ,4 , null , null , null),
('شاهين شهر و ميمه',null , null ,4 , null , null , null),
('شهر رضا',null , null ,4 , null , null , null),
('سميرم سفلي',null , null ,4 , null , null , null),
('فريدن',null , null ,4 , null , null , null),
('فريدون شهر',null , null ,4 , null , null , null),
('فلاورجان',null , null ,4 , null , null , null),
('كاشان',null , null ,4 , null , null , null),
('گلپايگان',null , null ,4 , null , null , null),
('لنجان',null , null ,4 , null , null , null),
('مباركه',null , null ,4 , null , null , null),
('نائين',null , null ,4 , null , null , null),
('نجف آباد',null , null ,4 , null , null , null),
('نطنز',null , null ,4 , null , null , null),
('ساوجبلاق',null , null ,5 , null , null , null),
('كرج',null , null ,5 , null , null , null),
('نظرآباد',null , null ,5 , null , null , null),
('طالقان',null , null ,5 , null , null , null),
('آبدانان',null , null ,6 , null , null , null),
('ايلام',null , null ,6 , null , null , null),
('ايوان',null , null ,6 , null , null , null),
('دره شهر',null , null ,6 , null , null , null),
('دهلران',null , null ,6 , null , null , null),
('شيران و چرداول',null , null ,6 , null , null , null),
('مهران',null , null ,6 , null , null , null),
('بوشهر',null , null ,7 , null , null , null),
('تنگستان',null , null ,7 , null , null , null),
('جم',null , null ,7 , null , null , null),
('دشتستان',null , null ,7 , null , null , null),
('دشتي',null , null ,7 , null , null , null),
('دير',null , null ,7 , null , null , null),
('ديلم',null , null ,7 , null , null , null),
('كنگان',null , null ,7 , null , null , null),
('گناوه',null , null ,7 , null , null , null),
('اسلام شهر',null , null ,8 , null , null , null),
('پاكدشت',null , null ,8 , null , null , null),
('تهران',null , null ,8 , null , null , null),
('دماوند',null , null ,8 , null , null , null),
('رباط كريم',null , null ,8 , null , null , null),
('ري',null , null ,8 , null , null , null),
('شميرانات',null , null ,8 , null , null , null),
('شهريار',null , null ,8 , null , null , null),
('فيروزكوه',null , null ,8 , null , null , null),
('ورامين',null , null ,8 , null , null , null),
('اردل',null , null ,9 , null , null , null),
('بروجن',null , null ,9 , null , null , null),
('شهركرد',null , null ,9 , null , null , null),
('فارسان',null , null ,9 , null , null , null),
('كوهرنگ',null , null ,9 , null , null , null),
('لردگان',null , null ,9 , null , null , null),
('بيرجند',null , null ,10 , null , null , null),
('درميان',null , null ,10 , null , null , null),
('سرايان',null , null ,10 , null , null , null),
('سر بيشه',null , null ,10 , null , null , null),
('فردوس',null , null ,10 , null , null , null),
('قائن',null , null ,10 , null , null , null),
('نهبندان',null , null ,10 , null , null , null),
('برد سكن',null , null ,11 , null , null , null),
('بجستان',null , null ,11 , null , null , null),
('تايباد',null , null ,11 , null , null , null),
('تحت جلگه',null , null ,11 , null , null , null),
('تربت جام',null , null ,11 , null , null , null),
('تربت حيدريه',null , null ,11 , null , null , null),
('چناران',null , null ,11 , null , null , null),
('جغتاي',null , null ,11 , null , null , null),
('جوين',null , null ,11 , null , null , null),
('خليل آباد',null , null ,11 , null , null , null),
('خواف',null , null ,11 , null , null , null),
('درگز',null , null ,11 , null , null , null),
('رشتخوار',null , null ,11 , null , null , null),
('زاوه',null , null ,11 , null , null , null),
('سبزوار',null , null ,11 , null , null , null),
('سرخس',null , null ,11 , null , null , null),
('فريمان',null , null ,11 , null , null , null),
('قوچان',null , null ,11 , null , null , null),
('طرقبه و شانديز',null , null ,11 , null , null , null),
('كاشمر',null , null ,11 , null , null , null),
('كلات',null , null ,11 , null , null , null),
('گناباد',null , null ,11 , null , null , null),
('مشهد',null , null ,11 , null , null , null),
('مه ولات',null , null ,11 , null , null , null),
('نيشابور',null , null ,11 , null , null , null),
('اسفراين',null , null ,12 , null , null , null),
('بجنورد',null , null ,12 , null , null , null),
('جاجرم',null , null ,12 , null , null , null),
('شيروان',null , null ,12 , null , null , null),
('فاروج',null , null ,12 , null , null , null),
('مانه و سملقان',null , null ,12 , null , null , null),
('آبادان',null , null ,13 , null , null , null),
('اميديه',null , null ,13 , null , null , null),
('انديمشك',null , null ,13 , null , null , null),
('اهواز',null , null ,13 , null , null , null),
('ايذه',null , null ,13 , null , null , null),
('باغ ملك',null , null ,13 , null , null , null),
('بندرماهشهر',null , null ,13 , null , null , null),
('بهبهان',null , null ,13 , null , null , null),
('خرمشهر',null , null ,13 , null , null , null),
('دزفول',null , null ,13 , null , null , null),
('دشت آزادگان',null , null ,13 , null , null , null),
('رامشير',null , null ,13 , null , null , null),
('رامهرمز',null , null ,13 , null , null , null),
('شادگان',null , null ,13 , null , null , null),
('شوش',null , null ,13 , null , null , null),
('شوشتر',null , null ,13 , null , null , null),
('گتوند',null , null ,13 , null , null , null),
('لالي',null , null ,13 , null , null , null),
('مسجد سليمان',null , null ,13 , null , null , null),
('هنديجان',null , null ,13 , null , null , null),
('ابهر',null , null ,14 , null , null , null),
('ايجرود',null , null ,14 , null , null , null),
('خدابنده',null , null ,14 , null , null , null),
('خرمدره',null , null ,14 , null , null , null),
('زنجان',null , null ,14 , null , null , null),
('طارم',null , null ,14 , null , null , null),
('ماه نشان',null , null ,14 , null , null , null),
('دامغان',null , null ,15 , null , null , null),
('سمنان',null , null ,15 , null , null , null),
('شاهرود',null , null ,15 , null , null , null),
('گرمسار',null , null ,15 , null , null , null),
('مهدي شهر',null , null ,15 , null , null , null),
('ايرانشهر',null , null ,16 , null , null , null),
('چابهار',null , null ,16 , null , null , null),
('خاش',null , null ,16 , null , null , null),
('دلگان',null , null ,16 , null , null , null),
('زابل',null , null ,16 , null , null , null),
('زاهدان',null , null ,16 , null , null , null),
('زهك',null , null ,16 , null , null , null),
('سراوان',null , null ,16 , null , null , null),
('سرباز',null , null ,16 , null , null , null),
('كنارك',null , null ,16 , null , null , null),
('نيكشهر',null , null ,16 , null , null , null),
('آباده',null , null ,17 , null , null , null),
('ارسنجان',null , null ,17 , null , null , null),
('استهبان',null , null ,17 , null , null , null),
('اقليد',null , null ,17 , null , null , null),
('بوانات',null , null ,17 , null , null , null),
('پاسارگاد',null , null ,17 , null , null , null),
('جهرم',null , null ,17 , null , null , null),
('خرم بيد',null , null ,17 , null , null , null),
('خنج',null , null ,17 , null , null , null),
('داراب',null , null ,17 , null , null , null),
('زرين دشت',null , null ,17 , null , null , null),
('سپيدان',null , null ,17 , null , null , null),
('شيراز',null , null ,17 , null , null , null),
('فراشبند',null , null ,17 , null , null , null),
('فسا',null , null ,17 , null , null , null),
('فيروزآباد',null , null ,17 , null , null , null),
('قير و كارزين',null , null ,17 , null , null , null),
('كازرون',null , null ,17 , null , null , null),
('لارستان',null , null ,17 , null , null , null),
('لامرد',null , null ,17 , null , null , null),
('مرودشت',null , null ,17 , null , null , null),
('ممسني',null , null ,17 , null , null , null),
('مهر',null , null ,17 , null , null , null),
('ني ريز',null , null ,17 , null , null , null),
('آبيك',null , null ,18 , null , null , null),
('البرز',null , null ,18 , null , null , null),
('بوئين زهرا',null , null ,18 , null , null , null),
('تاكستان',null , null ,18 , null , null , null),
('قزوين',null , null ,18 , null , null , null),
('قم',null , null ,19 , null , null , null),
('بانه',null , null ,20 , null , null , null),
('بيجار',null , null ,20 , null , null , null),
('ديواندره',null , null ,20 , null , null , null),
('سروآباد',null , null ,20 , null , null , null),
('سقز',null , null ,20 , null , null , null),
('سنندج',null , null ,20 , null , null , null),
('قروه',null , null ,20 , null , null , null),
('كامياران',null , null ,20 , null , null , null),
('مريوان',null , null ,20 , null , null , null),
('بافت',null , null ,21 , null , null , null),
('بردسير',null , null ,21 , null , null , null),
('بم',null , null ,21 , null , null , null),
('جيرفت',null , null ,21 , null , null , null),
('راور',null , null ,21 , null , null , null),
('رفسنجان',null , null ,21 , null , null , null),
('رودبار جنوب',null , null ,21 , null , null , null),
('زرند',null , null ,21 , null , null , null),
('سيرجان',null , null ,21 , null , null , null),
('شهر بابك',null , null ,21 , null , null , null),
('عنبرآباد',null , null ,21 , null , null , null),
('قلعه گنج',null , null ,21 , null , null , null),
('كرمان',null , null ,21 , null , null , null),
('كوهبنان',null , null ,21 , null , null , null),
('كهنوج',null , null ,21 , null , null , null),
('منوجان',null , null ,21 , null , null , null),
('اسلام آباد غرب',null , null ,22 , null , null , null),
('پاوه',null , null ,22 , null , null , null),
('ثلاث باباجاني',null , null ,22 , null , null , null),
('جوانرود',null , null ,22 , null , null , null),
('دالاهو',null , null ,22 , null , null , null),
('روانسر',null , null ,22 , null , null , null),
('سر پل ذهاب',null , null ,22 , null , null , null),
('سنقر',null , null ,22 , null , null , null),
('صحنه',null , null ,22 , null , null , null),
('قصر شيرين',null , null ,22 , null , null , null),
('كرمانشاه',null , null ,22 , null , null , null),
('كنگاور',null , null ,22 , null , null , null),
('گيلان غرب',null , null ,22 , null , null , null),
('هرسين',null , null ,22 , null , null , null),
('بوير احمد',null , null ,23 , null , null , null),
('بهمئي',null , null ,23 , null , null , null),
('دنا',null , null ,23 , null , null , null),
('كهگيلويه',null , null ,23 , null , null , null),
('گچساران',null , null ,23 , null , null , null),
('آزادشهر',null , null ,24 , null , null , null),
('آق قلا',null , null ,24 , null , null , null),
('بندر گز',null , null ,24 , null , null , null),
('بندر تركمن',null , null ,24 , null , null , null),
('راميان',null , null ,24 , null , null , null),
('علي آباد',null , null ,24 , null , null , null),
('كرد كوي',null , null ,24 , null , null , null),
('كلاله',null , null ,24 , null , null , null),
('گرگان',null , null ,24 , null , null , null),
('گنبد كاووس',null , null ,24 , null , null , null),
('مينو دشت',null , null ,24 , null , null , null),
('آستارا',null , null ,25 , null , null , null),
('آستانه اشرفيه',null , null ,25 , null , null , null),
('املش',null , null ,25 , null , null , null),
('بندر انزلي',null , null ,25 , null , null , null),
('رشت',null , null ,25 , null , null , null),
('رضوانشهر',null , null ,25 , null , null , null),
('رودبار',null , null ,25 , null , null , null),
('رودسر',null , null ,25 , null , null , null),
('سياهكل',null , null ,25 , null , null , null),
('شفت',null , null ,25 , null , null , null),
('صومعه سرا',null , null ,25 , null , null , null),
('طوالش',null , null ,25 , null , null , null),
('فومن',null , null ,25 , null , null , null),
('لاهيجان',null , null ,25 , null , null , null),
('لنگرود',null , null ,25 , null , null , null),
('ماسال',null , null ,25 , null , null , null),
('ازنا',null , null ,26 , null , null , null),
('اليگودرز',null , null ,26 , null , null , null),
('بروجرد',null , null ,26 , null , null , null),
('پلدختر',null , null ,26 , null , null , null),
('خرم آباد',null , null ,26 , null , null , null),
('دورود',null , null ,26 , null , null , null),
('لامرد',null , null ,17 , null , null , null),
('مرودشت',null , null ,17 , null , null , null),
('ممسني',null , null ,17 , null , null , null),
('مهر',null , null ,17 , null , null , null),
('ني ريز',null , null ,17 , null , null , null),
('آبيك',null , null ,18 , null , null , null),
('البرز',null , null ,18 , null , null , null),
('بوئين زهرا',null , null ,18 , null , null , null),
('تاكستان',null , null ,18 , null , null , null),
('قزوين',null , null ,18 , null , null , null),
('قم',null , null ,19 , null , null , null),
('بانه',null , null ,20 , null , null , null),
('بيجار',null , null ,20 , null , null , null),
('ديواندره',null , null ,20 , null , null , null),
('سروآباد',null , null ,20 , null , null , null),
('سقز',null , null ,20 , null , null , null),
('سنندج',null , null ,20 , null , null , null),
('قروه',null , null ,20 , null , null , null),
('كامياران',null , null ,20 , null , null , null),
('مريوان',null , null ,20 , null , null , null),
('بافت',null , null ,21 , null , null , null),
('بردسير',null , null ,21 , null , null , null),
('بم',null , null ,21 , null , null , null),
('جيرفت',null , null ,21 , null , null , null),
('راور',null , null ,21 , null , null , null),
('رفسنجان',null , null ,21 , null , null , null),
('رودبار جنوب',null , null ,21 , null , null , null),
('زرند',null , null ,21 , null , null , null),
('سيرجان',null , null ,21 , null , null , null),
('شهر بابك',null , null ,21 , null , null , null),
('عنبرآباد',null , null ,21 , null , null , null),
('قلعه گنج',null , null ,21 , null , null , null),
('كرمان',null , null ,21 , null , null , null),
('كوهبنان',null , null ,21 , null , null , null),
('كهنوج',null , null ,21 , null , null , null),
('منوجان',null , null ,21 , null , null , null),
('اسلام آباد غرب',null , null ,22 , null , null , null),
('پاوه',null , null ,22 , null , null , null),
('ثلاث باباجاني',null , null ,22 , null , null , null),
('جوانرود',null , null ,22 , null , null , null),
('دالاهو',null , null ,22 , null , null , null),
('روانسر',null , null ,22 , null , null , null),
('سر پل ذهاب',null , null ,22 , null , null , null),
('سنقر',null , null ,22 , null , null , null),
('صحنه',null , null ,22 , null , null , null),
('قصر شيرين',null , null ,22 , null , null , null),
('كرمانشاه',null , null ,22 , null , null , null),
('كنگاور',null , null ,22 , null , null , null),
('گيلان غرب',null , null ,22 , null , null , null),
('هرسين',null , null ,22 , null , null , null),
('بوير احمد',null , null ,23 , null , null , null),
('بهمئي',null , null ,23 , null , null , null),
('دنا',null , null ,23 , null , null , null),
('كهگيلويه',null , null ,23 , null , null , null),
('گچساران',null , null ,23 , null , null , null),
('آزادشهر',null , null ,24 , null , null , null),
('آق قلا',null , null ,24 , null , null , null),
('بندر گز',null , null ,24 , null , null , null),
('بندر تركمن',null , null ,24 , null , null , null),
('راميان',null , null ,24 , null , null , null),
('علي آباد',null , null ,24 , null , null , null),
('كرد كوي',null , null ,24 , null , null , null),
('كلاله',null , null ,24 , null , null , null),
('گرگان',null , null ,24 , null , null , null),
('گنبد كاووس',null , null ,24 , null , null , null),
('مينو دشت',null , null ,24 , null , null , null),
('آستارا',null , null ,25 , null , null , null),
('آستانه اشرفيه',null , null ,25 , null , null , null),
('املش',null , null ,25 , null , null , null),
('بندر انزلي',null , null ,25 , null , null , null),
('رشت',null , null ,25 , null , null , null),
('رضوانشهر',null , null ,25 , null , null , null),
('رودبار',null , null ,25 , null , null , null),
('رودسر',null , null ,25 , null , null , null),
('سياهكل',null , null ,25 , null , null , null),
('شفت',null , null ,25 , null , null , null),
('صومعه سرا',null , null ,25 , null , null , null),
('طوالش',null , null ,25 , null , null , null),
('فومن',null , null ,25 , null , null , null),
('لاهيجان',null , null ,25 , null , null , null),
('لنگرود',null , null ,25 , null , null , null),
('ماسال',null , null ,25 , null , null , null),
('ازنا',null , null ,26 , null , null , null),
('اليگودرز',null , null ,26 , null , null , null),
('بروجرد',null , null ,26 , null , null , null),
('پلدختر',null , null ,26 , null , null , null),
('خرم آباد',null , null ,26 , null , null , null),
('دورود',null , null ,26 , null , null , null),
('دلفان',null , null ,26 , null , null , null),
('سلسله',null , null ,26 , null , null , null),
('كوهدشت',null , null ,26 , null , null , null),
('الشتر',null , null ,26 , null , null , null),
('نورآباد',null , null ,26 , null , null , null),
('آمل',null , null ,27 , null , null , null),
('بابل',null , null ,27 , null , null , null),
('بابلسر',null , null ,27 , null , null , null),
('بهشهر',null , null ,27 , null , null , null),
('تنكابن',null , null ,27 , null , null , null),
('جويبار',null , null ,27 , null , null , null),
('چالوس',null , null ,27 , null , null , null),
('رامسر',null , null ,27 , null , null , null),
('ساري',null , null ,27 , null , null , null),
('سوادكوه',null , null ,27 , null , null , null),
('قائم شهر',null , null ,27 , null , null , null),
('گلوگاه',null , null ,27 , null , null , null),
('محمود آباد',null , null ,27 , null , null , null),
('نكا',null , null ,27 , null , null , null),
('نور',null , null ,27 , null , null , null),
('نوشهر',null , null ,27 , null , null , null),
('فريدونكنار',null , null ,27 , null , null , null),
('آشتيان',null , null ,28 , null , null , null),
('اراك',null , null ,28 , null , null , null),
('تفرش',null , null ,28 , null , null , null),
('خمين',null , null ,28 , null , null , null),
('دليجان',null , null ,28 , null , null , null),
('زرنديه',null , null ,28 , null , null , null),
('ساوه',null , null ,28 , null , null , null),
('شازند',null , null ,28 , null , null , null),
('كميجان',null , null ,28 , null , null , null),
('محلات',null , null ,28 , null , null , null),
('بندرعباس',null , null ,29 , null , null , null),
('ميناب',null , null ,29 , null , null , null),
('بندر لنگه',null , null ,29 , null , null , null),
('رودان-دهبارز',null , null ,29 , null , null , null),
('جاسك',null , null ,29 , null , null , null),
('قشم',null , null ,29 , null , null , null),
('حاجي آباد',null , null ,29 , null , null , null),
('ابوموسي',null , null ,29 , null , null , null),
('بستك',null , null ,29 , null , null , null),
('گاوبندي',null , null ,29 , null , null , null),
('خمير',null , null ,29 , null , null , null),
('اسدآباد',null , null ,30 , null , null , null),
('بهار',null , null ,30 , null , null , null),
('تويسركان',null , null ,30 , null , null , null),
('رزن',null , null ,30 , null , null , null),
('كبودر آهنگ',null , null ,30 , null , null , null),
('ملاير',null , null ,30 , null , null , null),
('نهاوند',null , null ,30 , null , null , null),
('همدان',null , null ,30 , null , null , null),
('ابركوه',null , null ,31 , null , null , null),
('اردكان',null , null ,31 , null , null , null),
('بافق',null , null ,31 , null , null , null),
('تفت',null , null ,31 , null , null , null),
('خاتم',null , null ,31 , null , null , null),
('صدوق',null , null ,31 , null , null , null),
('طبس',null , null ,31 , null , null , null),
('مهريز',null , null ,31 , null , null , null),
('ميبد',null , null ,31 , null , null , null),
('يزد',null , null ,31 , null , null , null);
