INSERT INTO `states` (`country_id`,`state_name_fa`,`state_name_en`,`state_name_ar`,`deleted_at`,`created_at`,`updated_at`) VALUES
(1,'آذربايجان شرقی',null,null,null,null,null),
(1,'آذربايجان غربی',null,null,null,null,null),
(1,'اردبيل',null,null,null,null,null),
(1,'اصفهان',null,null,null,null,null),
(1,'البرز',null,null,null,null,null),
(1,'ايلام',null,null,null,null,null),
(1,'بوشهر',null,null,null,null,null),
(1,'تهران',null,null,null,null,null),
(1,'چهارمحال و بختیاری',null,null,null,null,null),
(1,'خراسان جنوبي',null,null,null,null,null),
(1,'خراسان رضوی',null,null,null,null,null),
(1,'خراسان شمالی',null,null,null,null,null),
(1,'خوزستان',null,null,null,null,null),
(1,'زنجان',null,null,null,null,null),
(1,'سمنان',null,null,null,null,null),
(1,'سيستان و بلوچستان',null,null,null,null,null),
(1,'فارس',null,null,null,null,null),
(1,'قزوين',null,null,null,null,null),
(1,'قم',null,null,null,null,null),
(1,'كردستان',null,null,null,null,null),
(1,'كرمان',null,null,null,null,null),
(1,'كرمانشاه',null,null,null,null,null),
(1,'كهگيلويه و بويراحمد',null,null,null,null,null),
(1,'گلستان',null,null,null,null,null),
(1,'گيلان',null,null,null,null,null),
(1,'لرستان',null,null,null,null,null),
(1,'مازندران',null,null,null,null,null),
(1,'مرکزی',null,null,null,null,null),
(1,'هرمزگان',null,null,null,null,null),
(1,'همدان',null,null,null,null,null),
(1,'يزد',null,null,null,null,null);